// ── PowerPoint Generator — 8 slides from audit data ──
import PptxGenJS from "pptxgenjs";
import { AuditResult } from "./auditEngine";

const DARK = "1a1f2e";
const WHITE = "FFFFFF";
const ACCENT = "3b82d4";
const RED = "ef4444";
const GREEN = "22c55e";
const YELLOW = "f59e0b";
const MUTED = "57606a";
const LIGHT = "f7f8fa";

function fmt$(n: number): string {
  if (n >= 1000000) return `$${(n / 1000000).toFixed(1)}M`;
  if (n >= 1000) return `$${(n / 1000).toFixed(1)}K`;
  return `$${n.toFixed(0)}`;
}
function fmtPct(n: number): string {
  return `${(n * 100).toFixed(1)}%`;
}

function addHeader(slide: PptxGenJS.Slide, title: string, subtitle?: string) {
  slide.addShape("rect", { x: 0, y: 0, w: "100%", h: 1.1, fill: { color: DARK } });
  slide.addText(title, { x: 0.4, y: 0.18, w: 8, h: 0.5, fontSize: 22, bold: true, color: WHITE, fontFace: "Segoe UI" });
  if (subtitle) {
    slide.addText(subtitle, { x: 0.4, y: 0.68, w: 8, h: 0.3, fontSize: 11, color: "8b949e", fontFace: "Segoe UI" });
  }
}

function addFooter(slide: PptxGenJS.Slide, pageNum: number) {
  slide.addShape("line", { x: 0.4, y: 7.0, w: 9.2, h: 0, line: { color: "e5e7eb", width: 0.5 } });
  slide.addText(`Generated by AuditAI  •  Page ${pageNum}`, {
    x: 0.4, y: 7.1, w: 9.2, h: 0.3, fontSize: 9, color: MUTED, align: "right", fontFace: "Segoe UI",
  });
}

function scoreColor(score: number): string {
  if (score >= 80) return GREEN;
  if (score >= 65) return YELLOW;
  return RED;
}

export async function generatePptx(audit: AuditResult, brandName = "Your Account"): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "AuditAI";
  pptx.title = `${brandName} — Campaign Audit Report`;

  const { summary, score, scoreLabel, spendEfficiency, structureQuality, totalWeeklyWaste, totalMonthlyOpportunity, findings, topWaste, topOpportunities, asinCohorts } = audit;

  // ── SLIDE 1: Title ──
  const s1 = pptx.addSlide();
  s1.addShape("rect", { x: 0, y: 0, w: "100%", h: "100%", fill: { color: DARK } });
  s1.addShape("rect", { x: 0, y: 5.5, w: "100%", h: 2, fill: { color: ACCENT } });
  s1.addText("Campaign Audit Report", { x: 0.6, y: 1.8, w: 9, h: 0.8, fontSize: 36, bold: true, color: WHITE, fontFace: "Segoe UI" });
  s1.addText(brandName, { x: 0.6, y: 2.7, w: 9, h: 0.5, fontSize: 20, color: "8b949e", fontFace: "Segoe UI" });
  s1.addText(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), {
    x: 0.6, y: 3.3, w: 9, h: 0.4, fontSize: 14, color: "8b949e", fontFace: "Segoe UI",
  });
  s1.addText("Powered by AuditAI", { x: 0.6, y: 6.0, w: 9, h: 0.4, fontSize: 13, color: WHITE, fontFace: "Segoe UI" });

  // ── SLIDE 2: Executive Summary ──
  const s2 = pptx.addSlide();
  addHeader(s2, "Executive Summary", `${summary.campaignCount} campaigns · ${summary.keywordCount} keywords · ${summary.asinCount} ASINs analyzed`);

  // Score circle
  s2.addShape("ellipse", { x: 0.4, y: 1.4, w: 2.4, h: 2.4, fill: { color: LIGHT }, line: { color: scoreColor(score), width: 6 } });
  s2.addText(String(score), { x: 0.4, y: 2.0, w: 2.4, h: 0.9, fontSize: 48, bold: true, color: scoreColor(score), align: "center", fontFace: "Segoe UI" });
  s2.addText(scoreLabel, { x: 0.4, y: 3.0, w: 2.4, h: 0.3, fontSize: 11, color: scoreColor(score), align: "center", fontFace: "Segoe UI" });
  s2.addText("Health Score", { x: 0.4, y: 3.3, w: 2.4, h: 0.3, fontSize: 10, color: MUTED, align: "center", fontFace: "Segoe UI" });

  // Key metrics
  const metrics = [
    { label: "Weekly Spend", val: fmt$(summary.totalSpend), color: DARK },
    { label: "Weekly Sales", val: fmt$(summary.totalSales), color: GREEN },
    { label: "Weekly Waste", val: fmt$(totalWeeklyWaste), color: RED },
    { label: "Monthly Opp.", val: fmt$(totalMonthlyOpportunity), color: ACCENT },
    { label: "Avg ACOS", val: fmtPct(summary.avgAcos), color: DARK },
    { label: "Avg CVR", val: fmtPct(summary.avgCvr), color: DARK },
  ];
  metrics.forEach((m, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = 3.2 + col * 2.2;
    const y = 1.4 + row * 1.6;
    s2.addShape("rect", { x, y, w: 2.0, h: 1.3, fill: { color: LIGHT }, line: { color: "e5e7eb", width: 0.5 }, rectRadius: 0.1 });
    s2.addText(m.val, { x, y: y + 0.2, w: 2.0, h: 0.6, fontSize: 22, bold: true, color: m.color, align: "center", fontFace: "Segoe UI" });
    s2.addText(m.label, { x, y: y + 0.8, w: 2.0, h: 0.3, fontSize: 10, color: MUTED, align: "center", fontFace: "Segoe UI" });
  });

  // Top action
  s2.addShape("rect", { x: 0.4, y: 5.0, w: 9.2, h: 0.7, fill: { color: "fef3c7" }, line: { color: "fde68a", width: 0.5 }, rectRadius: 0.1 });
  s2.addText(`⚡ Top Action: ${topWaste[0]?.action ?? "Review campaign structure"}`, {
    x: 0.6, y: 5.1, w: 8.8, h: 0.45, fontSize: 12, bold: true, color: "92400e", fontFace: "Segoe UI",
  });
  addFooter(s2, 2);

  // ── SLIDE 3: Account Scorecard ──
  const s3 = pptx.addSlide();
  addHeader(s3, "Account Scorecard", "Health score breakdown by category");

  const scoreItems = [
    { label: "Spend Efficiency", score: spendEfficiency, max: 70, desc: "Waste ratio, ACOS performance, zero-return campaigns" },
    { label: "Structure Quality", score: structureQuality, max: 30, desc: "Negative keywords, campaign structure, concentration risk" },
  ];
  scoreItems.forEach((item, i) => {
    const y = 1.4 + i * 2.0;
    s3.addText(item.label, { x: 0.4, y, w: 4, h: 0.4, fontSize: 14, bold: true, color: DARK, fontFace: "Segoe UI" });
    s3.addText(item.desc, { x: 0.4, y: y + 0.4, w: 6, h: 0.3, fontSize: 10, color: MUTED, fontFace: "Segoe UI" });
    const barW = 8.0;
    const fillW = (item.score / item.max) * barW;
    s3.addShape("rect", { x: 0.4, y: y + 0.8, w: barW, h: 0.4, fill: { color: "e5e7eb" }, rectRadius: 0.1 });
    s3.addShape("rect", { x: 0.4, y: y + 0.8, w: Math.max(0.1, fillW), h: 0.4, fill: { color: scoreColor((item.score / item.max) * 100) }, rectRadius: 0.1 });
    s3.addText(`${item.score}/${item.max}`, { x: 8.5, y: y + 0.8, w: 1, h: 0.4, fontSize: 13, bold: true, color: scoreColor((item.score / item.max) * 100), fontFace: "Segoe UI" });
  });

  s3.addText(`Overall Health Score: ${score}/100 — ${scoreLabel}`, {
    x: 0.4, y: 5.8, w: 9.2, h: 0.5, fontSize: 16, bold: true, color: scoreColor(score), align: "center", fontFace: "Segoe UI",
  });
  addFooter(s3, 3);

  // ── SLIDE 4: Budget Waste Analysis ──
  const s4 = pptx.addSlide();
  addHeader(s4, "Budget Waste Analysis", `${fmt$(totalWeeklyWaste)}/week recoverable · ${fmt$(totalWeeklyWaste * 52)}/year`);

  topWaste.slice(0, 4).forEach((f, i) => {
    const y = 1.3 + i * 1.3;
    s4.addShape("rect", { x: 0.4, y, w: 0.06, h: 1.0, fill: { color: f.severity === "critical" ? RED : YELLOW } });
    s4.addText(f.title, { x: 0.6, y: y + 0.05, w: 7.0, h: 0.4, fontSize: 12, bold: true, color: DARK, fontFace: "Segoe UI" });
    s4.addText(f.detail, { x: 0.6, y: y + 0.42, w: 7.0, h: 0.28, fontSize: 10, color: MUTED, fontFace: "Segoe UI" });
    s4.addText(`▶ ${f.action}`, { x: 0.6, y: y + 0.68, w: 7.2, h: 0.25, fontSize: 10, bold: true, color: RED, fontFace: "Segoe UI" });
    s4.addText(fmt$(f.impact) + "/wk", { x: 8.0, y: y + 0.2, w: 1.6, h: 0.4, fontSize: 14, bold: true, color: RED, align: "right", fontFace: "Segoe UI" });
  });
  addFooter(s4, 4);

  // ── SLIDE 5: Keyword Audit ──
  const s5 = pptx.addSlide();
  const kwFindings = findings.filter((f) => f.id.startsWith("kw-"));
  addHeader(s5, "Keyword Audit", `${kwFindings.length} keyword issues found`);

  const kwWaste = findings.filter((f) => f.id.startsWith("kw-waste")).length;
  const kwAcos = findings.filter((f) => f.id.startsWith("kw-acos")).length;
  const kwCtr = findings.filter((f) => f.id.startsWith("kw-ctr")).length;

  const kwStats = [
    { label: "High Spend\nNo Sales", val: kwWaste, color: RED },
    { label: "High ACOS\n(>75%)", val: kwAcos, color: YELLOW },
    { label: "Low CTR\n(<0.1%)", val: kwCtr, color: "f97316" },
  ];
  kwStats.forEach((s, i) => {
    const x = 0.4 + i * 3.2;
    s5.addShape("rect", { x, y: 1.3, w: 2.8, h: 1.4, fill: { color: LIGHT }, line: { color: "e5e7eb", width: 0.5 }, rectRadius: 0.1 });
    s5.addText(String(s.val), { x, y: 1.45, w: 2.8, h: 0.7, fontSize: 36, bold: true, color: s.color, align: "center", fontFace: "Segoe UI" });
    s5.addText(s.label, { x, y: 2.2, w: 2.8, h: 0.4, fontSize: 10, color: MUTED, align: "center", fontFace: "Segoe UI" });
  });

  kwFindings.slice(0, 3).forEach((f, i) => {
    const y = 3.0 + i * 1.1;
    s5.addText(`${f.title}`, { x: 0.4, y, w: 7.5, h: 0.35, fontSize: 11, bold: true, color: DARK, fontFace: "Segoe UI" });
    s5.addText(`${f.detail}  ▶ ${f.action}`, { x: 0.4, y: y + 0.35, w: 9.0, h: 0.28, fontSize: 10, color: MUTED, fontFace: "Segoe UI" });
  });
  addFooter(s5, 5);

  // ── SLIDE 6: Search Term Opportunities ──
  const s6 = pptx.addSlide();
  const stFindings = findings.filter((f) => f.id.startsWith("st-"));
  addHeader(s6, "Search Term Analysis", `${stFindings.filter(f => f.category === 'waste').length} wasted terms · ${stFindings.filter(f => f.category === 'opportunity').length} opportunities`);

  topOpportunities.slice(0, 4).forEach((f, i) => {
    const y = 1.3 + i * 1.3;
    s6.addShape("rect", { x: 0.4, y, w: 0.06, h: 1.0, fill: { color: GREEN } });
    s6.addText(f.title, { x: 0.6, y: y + 0.05, w: 7.2, h: 0.4, fontSize: 12, bold: true, color: DARK, fontFace: "Segoe UI" });
    s6.addText(f.detail, { x: 0.6, y: y + 0.42, w: 7.2, h: 0.28, fontSize: 10, color: MUTED, fontFace: "Segoe UI" });
    s6.addText(`▶ ${f.action}`, { x: 0.6, y: y + 0.68, w: 7.2, h: 0.25, fontSize: 10, bold: true, color: "166534", fontFace: "Segoe UI" });
    s6.addText(`+${fmt$(f.impact * 4)}/mo`, { x: 8.0, y: y + 0.2, w: 1.6, h: 0.4, fontSize: 14, bold: true, color: GREEN, align: "right", fontFace: "Segoe UI" });
  });

  if (topOpportunities.length === 0) {
    s6.addText("Upload a Search Term report to unlock opportunity analysis.", {
      x: 0.4, y: 3.0, w: 9.2, h: 0.5, fontSize: 13, color: MUTED, align: "center", fontFace: "Segoe UI",
    });
  }
  addFooter(s6, 6);

  // ── SLIDE 7: ASIN Cohort Analysis ──
  const s7 = pptx.addSlide();
  const cows = asinCohorts.filter((a) => a.cohort === "cash_cow");
  const love = asinCohorts.filter((a) => a.cohort === "need_love");
  const reduce = asinCohorts.filter((a) => a.cohort === "reduce_pause");
  addHeader(s7, "ASIN Cohort Analysis", `${asinCohorts.length} ASINs classified`);

  const cohortStats = [
    { label: "Cash Cows", val: cows.length, sub: "Top 80% of sales\n→ Protect & scale", color: GREEN },
    { label: "Need More Love", val: love.length, sub: "High CVR, low volume\n→ Increase budget", color: YELLOW },
    { label: "Reduce / Pause", val: reduce.length, sub: "Low CVR, low sales\n→ Reduce ad spend", color: RED },
  ];
  cohortStats.forEach((s, i) => {
    const x = 0.4 + i * 3.2;
    s7.addShape("rect", { x, y: 1.3, w: 2.8, h: 2.2, fill: { color: LIGHT }, line: { color: "e5e7eb", width: 1 }, rectRadius: 0.15 });
    s7.addText(String(s.val), { x, y: 1.4, w: 2.8, h: 0.9, fontSize: 48, bold: true, color: s.color, align: "center", fontFace: "Segoe UI" });
    s7.addText(s.label, { x, y: 2.35, w: 2.8, h: 0.35, fontSize: 12, bold: true, color: DARK, align: "center", fontFace: "Segoe UI" });
    s7.addText(s.sub, { x, y: 2.72, w: 2.8, h: 0.6, fontSize: 10, color: MUTED, align: "center", fontFace: "Segoe UI" });
  });

  if (cows[0]) {
    s7.addText(`Top Cash Cow: ${cows[0].asin}  |  CVR: ${fmtPct(cows[0].cvr)}  |  Sales: ${fmt$(cows[0].sales)}  →  Prioritize ad budget here`, {
      x: 0.4, y: 3.8, w: 9.2, h: 0.4, fontSize: 11, color: "166534", fontFace: "Segoe UI",
    });
  }
  addFooter(s7, 7);

  // ── SLIDE 8: 30-Day Action Plan ──
  const s8 = pptx.addSlide();
  addHeader(s8, "30-Day Action Plan", "Prioritized by dollar impact");

  const actions = [
    ...topWaste.slice(0, 3).map((f, i) => ({ week: "Week 1", priority: i + 1, action: f.action, impact: `Save ${fmt$(f.impact)}/week`, color: RED })),
    ...topOpportunities.slice(0, 2).map((f, i) => ({ week: "Week 2", priority: i + 4, action: f.action, impact: `+${fmt$(f.impact * 4)}/month`, color: GREEN })),
    { week: "Week 3–4", priority: 6, action: "Add negative keywords to top 5 campaigns", impact: "Improve CTR by ~20%", color: ACCENT },
    { week: "Week 3–4", priority: 7, action: "Review ASIN cohorts — shift budget to Cash Cows", impact: `+${fmt$(totalMonthlyOpportunity * 0.3)}/month`, color: ACCENT },
  ];

  actions.slice(0, 6).forEach((a, i) => {
    const y = 1.3 + i * 0.88;
    s8.addShape("ellipse", { x: 0.4, y: y + 0.14, w: 0.44, h: 0.44, fill: { color: a.color } });
    s8.addText(String(a.priority), { x: 0.4, y: y + 0.14, w: 0.44, h: 0.44, fontSize: 13, bold: true, color: WHITE, align: "center", fontFace: "Segoe UI" });
    s8.addText(`[${a.week}]`, { x: 1.0, y, w: 1.4, h: 0.3, fontSize: 9, color: MUTED, fontFace: "Segoe UI" });
    s8.addText(a.action, { x: 1.0, y: y + 0.28, w: 7.0, h: 0.35, fontSize: 11, bold: true, color: DARK, fontFace: "Segoe UI" });
    s8.addText(a.impact, { x: 8.2, y: y + 0.28, w: 1.4, h: 0.35, fontSize: 11, bold: true, color: a.color, align: "right", fontFace: "Segoe UI" });
  });

  addFooter(s8, 8);

  // ── Generate buffer ──
  const data = await pptx.write({ outputType: "nodebuffer" });
  return data as Buffer;
}
